### ISSUE TITLE
Add X-EconomicAppIdentifier header to Savon client init

### ISSUE THREAD

**Issue by vbklv** [lokalebasen/rconomic#39]
Since 16.11.2015 e-conomic require a X-EconomicAppIdentifier header to be set.
Currently the rconomic gem does not support this header which needs to be fixed.

**Comment by koppen** [comment]
Thanks for bringing this up. Rconomic currently supports two authentication schemes:

1. `Session#connect_with_credentials` (which uses to [Connect](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=Connect))
2. `Session#connect_with_token` (which uses to [ConnectWithToken](https://api.e-conomic.com/secure/api1/EconomicWebService.asmx?op=ConnectWithToken))

As far as I can tell, the `X-EconomicAppIdentifier` is not required when using `connect_with_token`.

[e-conomics recommendation](http://techtalk.e-conomic.com/e-conomic-soap-api-now-requires-you-to-specify-a-custom-x-economicappidentifier-header/#_ga=1.100088862.1634818109.1448480903) if you're using `Connect` is

> For users of the “Connect” method, we strongly recommend switching to our token authentication. In SOAP this is done via the ConnectWithToken method.

My initial recommendation is the same; Switch to `connect_with_token` until someone implements the header in rconomic. Pull requests are always appreciated.

**Comment by vbklv** [comment]
Sure. Thanks :)
